### ISSUE TITLE
Problem installing the demo

### ISSUE THREAD

**Issue by sadplace** [udos86/ng2-dynamic-forms#231]
Hi,

I follow the steps you have in "Running the example" but i get an error and the page does not open.
Can you help me? Maybe i am missing something ?
The npm run tsc says:

example/app/app.component.e2e.spec.ts(4,9): error TS2304: Cannot find name 'browser'.
example/app/app.component.e2e.spec.ts(8,16): error TS2304: Cannot find name 'browser'.
example/app/app.module.ts(11,43): error TS2307: Cannot find module '@ng2-dynamic-forms/ui-kendo'.
example/app/basic/basic-example.component.e2e.spec.ts(9,9): error TS2304: Cannot find name 'browser'.
example/app/basic/basic-example.component.e2e.spec.ts(16,20): error TS2304: Cannot find name 'element'.
example/app/basic/basic-example.component.e2e.spec.ts(16,28): error TS2304: Cannot find name 'by'.
example/app/basic/basic-example.component.e2e.spec.ts(22,9): error TS2304: Cannot find name 'element'.
example/app/basic/basic-example.component.e2e.spec.ts(22,21): error TS2304: Cannot find name 'by'.
example/app/basic/basic-example.component.e2e.spec.ts(26,55): error TS2346: Supplied parameters do not match any signature of call target.
example/app/basic/basic-example.component.e2e.spec.ts(37,24): error TS2304: Cannot find name 'element'.
example/app/basic/basic-example.component.e2e.spec.ts(37,32): error TS2304: Cannot find name 'by'.
example/app/basic/basic-example.component.e2e.spec.ts(38,44): error TS2346: Supplied parameters do not match any signature of call target.
17:42:31 - Compilation complete. Watching for file changes.
17:45:26 - File change detected. Starting incremental compilation...

i got this error in my browser:
Failed to load resource: the server responded with a status of 404 (Not Found)
zone.min.js:1 Unhandled Promise rejection: (SystemJS) XHR error (404 Not Found) loading http://localhost:3001/node_modules/@ng2-dynamic-forms/ui-kendo/bundles/ui-kendo.umd.min.js
	Error: XHR error (404 Not Found) loading http://localhost:3001/node_modules/@ng2-dynamic-forms/ui-kendo/bundles/ui-kendo.umd.min.js
	    at d (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:10968)
	    at XMLHttpRequest.t [as _onreadystatechange] (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:871)
	    at e.invokeTask (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:16940)
	    at t.runTask (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:13742)
	    at XMLHttpRequest.invoke (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:18080)
	Error loading http://localhost:3001/node_modules/@ng2-dynamic-forms/ui-kendo/bundles/ui-kendo.umd.min.js as "@ng2-dynamic-forms/ui-kendo" from http://localhost:3001/example/app/app.module.js ; Zone: <root> ; Task: Promise.then ; Value: Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3001/node_modules/@ng2-dynamic-forms/ui-kendo/bundles/ui-kendo.umd.min.js
	Error: XHR error (404 Not Found) loading http://localhost:3001/node_modules/@ng2-dynamic-forms/ui-kendo/bundles/ui-kendo.umd.min.js
	    at d (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:10968)
	    at XMLHttpRequest.t [as _onreadystatechange] (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:871)
	    at e.invokeTask (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:16940)
	    at t.runTask (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:13742)
	    at XMLHttpRequest.invoke (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:18080)
	Error loading http://localhost:3001/node_modules/@ng2-dynamic-forms/ui-kendo/bundles/ui-kendo.umd.min.js as "@ng2-dynamic-forms/ui-kendo" from http://localhost:3001/example/app/app.module.js
	    at d (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:10968)
	    at XMLHttpRequest.t [as _onreadystatechange] (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:871)
	    at e.invokeTask (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:16940)
	    at t.runTask (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:13742)
	    at XMLHttpRequest.invoke (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:18080)
	Error loading http://localhost:3001/node_modules/@ng2-dynamic-forms/ui-kendo/bundles/ui-kendo.umd.min.js as "@ng2-dynamic-forms/ui-kendo" from http://localhost:3001/example/app/app.module.js (SystemJS) XHR error (404 Not Found) loading http://localhost:3001/node_modules/@ng2-dynamic-forms/ui-kendo/bundles/ui-kendo.umd.min.js
	Error: XHR error (404 Not Found) loading http://localhost:3001/node_modules/@ng2-dynamic-forms/ui-kendo/bundles/ui-kendo.umd.min.js
	    at d (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:10968)
	    at XMLHttpRequest.t [as _onreadystatechange] (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:871)
	    at e.invokeTask (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:16940)
	    at t.runTask (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:13742)
	    at XMLHttpRequest.invoke (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:18080)
	Error loading http://localhost:3001/node_modules/@ng2-dynamic-forms/ui-kendo/bundles/ui-kendo.umd.min.js as "@ng2-dynamic-forms/ui-kendo" from http://localhost:3001/example/app/app.module.js
o @ zone.min.js:1
zone.min.js:1 Error: Uncaught (in promise): Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3001/node_modules/@ng2-dynamic-forms/ui-kendo/bundles/ui-kendo.umd.min.js
	Error: XHR error (404 Not Found) loading http://localhost:3001/node_modules/@ng2-dynamic-forms/ui-kendo/bundles/ui-kendo.umd.min.js
	    at d (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:10968)
	    at XMLHttpRequest.t [as _onreadystatechange] (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:871)
	    at e.invokeTask (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:16940)
	    at t.runTask (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:13742)
	    at XMLHttpRequest.invoke (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:18080)
	Error loading http://localhost:3001/node_modules/@ng2-dynamic-forms/ui-kendo/bundles/ui-kendo.umd.min.js as "@ng2-dynamic-forms/ui-kendo" from http://localhost:3001/example/app/app.module.js
(SystemJS) XHR error (404 Not Found) loading http://localhost:3001/node_modules/@ng2-dynamic-forms/ui-kendo/bundles/ui-kendo.umd.min.js
	Error: XHR error (404 Not Found) loading http://localhost:3001/node_modules/@ng2-dynamic-forms/ui-kendo/bundles/ui-kendo.umd.min.js
	    at d (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:10968)
	    at XMLHttpRequest.t [as _onreadystatechange] (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:871)
	    at e.invokeTask (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:16940)
	    at t.runTask (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:13742)
	    at XMLHttpRequest.invoke (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:18080)
	Error loading http://localhost:3001/node_modules/@ng2-dynamic-forms/ui-kendo/bundles/ui-kendo.umd.min.js as "@ng2-dynamic-forms/ui-kendo" from http://localhost:3001/example/app/app.module.js
	    at d (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:10968)
	    at XMLHttpRequest.t [as _onreadystatechange] (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:871)
	    at e.invokeTask (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:16940)
	    at t.runTask (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:13742)
	    at XMLHttpRequest.invoke (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:18080)
	Error loading http://localhost:3001/node_modules/@ng2-dynamic-forms/ui-kendo/bundles/ui-kendo.umd.min.js as "@ng2-dynamic-forms/ui-kendo" from http://localhost:3001/example/app/app.module.js
(SystemJS) XHR error (404 Not Found) loading http://localhost:3001/node_modules/@ng2-dynamic-forms/ui-kendo/bundles/ui-kendo.umd.min.js
	Error: XHR error (404 Not Found) loading http://localhost:3001/node_modules/@ng2-dynamic-forms/ui-kendo/bundles/ui-kendo.umd.min.js
	    at d (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:10968)
	    at XMLHttpRequest.t [as _onreadystatechange] (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:871)
	    at e.invokeTask (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:16940)
	    at t.runTask (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:13742)
	    at XMLHttpRequest.invoke (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:18080)
	Error loading http://localhost:3001/node_modules/@ng2-dynamic-forms/ui-kendo/bundles/ui-kendo.umd.min.js as "@ng2-dynamic-forms/ui-kendo" from http://localhost:3001/example/app/app.module.js
    at d (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:10968)
    at l (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:10393)
    at l (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:10216)
    at http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:10756
    at e.invokeTask (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:16940)
    at t.runTask (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:13742)
    at a (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:9811)
    at XMLHttpRequest.invoke (http://localhost:3001/node_modules/zone.js/dist/zone.min.js:1:18120)

**Comment by udos86** [comment]
@sadplace Sorry for that! I fixed the example to run without Kendo UI dependencies.

**Comment by udos86** [comment]
@sadplace Please ignore the type errors. They do occur because of missing Protractor types. You can start the app anyway.
