### ISSUE TITLE
Unable to run example --Did not detect a `bs-config.json` or `bs-config.js` override file. Using lite-server default ** browser-sync config **

### ISSUE THREAD

**Issue by jainrohit4ever** [udos86/ng2-dynamic-forms#238]
Getting the following error when trying to npm start the project.

Did not detect a `bs-config.json` or `bs-config.js` override file. Using lite-server default
** browser-sync config **

**Comment by udos86** [comment]
@jainrohit4ever You need to execute `npm start` at the root of your cloned git repository.

**Comment by jainrohit4ever** [comment]
@udos86 I am using the root directory.

Below are the steps followed 
1. git clone the project(master branch)
2. npm install
3. npm run tsc
4. npm start
It gives following error

```
(function (exports, require, module, __filename, __dirname) { let indexPath = ".                                                                                                                /example/index.html";
                                                              ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet sup                                                                                                                ported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at start (D:\recruit\ng2-dynamic forms\new\ng2-dynamic-forms\node_modules\li                                                                                                                te-server\lib\lite-server.js:27:17)
    at Object.<anonymous> (D:\recruit\ng2-dynamic forms\new\ng2-dynamic-forms\no                                                                                                                de_modules\lite-server\bin\lite-server:7:30)
    at Module._compile (module.js:409:26)
```
5. Added 'use strict'; on line 1 of browsersync.config.js 
6. npm start. Getting below error
```
> lite-server -c browsersync.config.js

Did not detect a `bs-config.json` or `bs-config.js` override file. Using lite-server defaults...
** browser-sync config **
{ injectChanges: false,
  files: [ './**/*.{html,htm,css,js}' ],
  watchOptions: { ignored: 'node_modules' },
  server: { baseDir: './', middleware: [ [Function], [Function] ] } }
```
Tried the same with multiple checkouts on multiple systems.
Would really appreciate any help here.

**Comment by udos86** [comment]
@jainrohit4ever Which version of Node are you running?

**Comment by jainrohit4ever** [comment]
Solved the problem, it was because of missing module connect-history-api-fallback.
Solved the problem by installing the module
Thanks @udos86

**Comment by Sanjeev-kumaar008** [comment]
same problem over here help me to solve
