### ISSUE TITLE
Error when testing ng2-dynamic-forms with angular-cli rc.2

### ISSUE THREAD

**Issue by mlegenhausen** [udos86/ng2-dynamic-forms#300]
When I run `ng test` with the most recent version of angular and angular-cli I get the following error:

```
ERROR in ./~/@ng2-dynamic-forms/ui-bootstrap/src/dynamic-form-bootstrap.component.ts
Module build failed: TypeError: Cannot read property 'getChildAt' of undefined
    at refactor.findAstNodes.filter.forEach (xxx/services/admin/node_modules/@ngtools/webpack/src/loader.js:222:54)
    at Array.forEach (native)
    at _removeModuleId (xxx/services/admin/node_modules/@ngtools/webpack/src/loader.js:215:10)
    at Promise.resolve.then.then (xxx/services/admin/node_modules/@ngtools/webpack/src/loader.js:299:33)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./~/@ng2-dynamic-forms/ui-bootstrap/index.js 6:9-58
 @ ./src/app/shared/shared.module.ts
 @ ./src/app/shops/shops.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
```

The problem is that `module.id` has no parent element which `@ngtools/webpack` wants to access. When I force `angular-cli` to use the bundled version I only get the error

```
ERROR in DynamicFormsBootstrapUIModule is not an NgModule
```

My current fix is to patch `dynamic-form-bootstrap.component.ts` and remove the `moduleId: module.id` from the file. This solves the problem.

Here the script if someone is interested:

```bash
#!/bin/sh

set -e

sed -i.bak "/moduleId: module.id,/d" "./node_modules/@ng2-dynamic-forms/ui-bootstrap/src/dynamic-form-bootstrap.component.ts"
```

**Comment by udos86** [comment]
@mlegenhausen Thanks for giving this information! I'll add a task to my build pipeline to remove `module.id`.
