### ISSUE TITLE
Runtime error : custom validator on a non-required field

### ISSUE THREAD

**Issue by arjunshankar** [udos86/ng2-dynamic-forms#369]
I am writing a validator for a non-required field. My validation function is as follows..
 
`function someValidator(fc:FormControl) {
  let isValid:boolean;
    if(fc.value == null || fc.value ==""){// works fine if i send back invalid when value is null.
      isValid = true;
    }
    else {
      if(logic..){
        isValid = true;
      }
      else{
        isValid = false;
      }
    }

  if(isValid){
    return null;
  }
  else{
    return {
      someValidator: {
        valid: false
      }
    };
  }

}`

Basically I want that my form should be valid if the field remains untouched or is set to blank. However, if I do want to set it... it should be properly formed. 

Getting the following error in this case.

_ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'hasOwnProperty' of null
TypeError: Cannot read property 'hasOwnProperty' of null
    at http://localhost:4200/vendor.bundle.js:53198:140
    at Array.find (native)
    at DynamicFormService.getCustomValidatorFn (http://localhost:4200/vendor.bundle.js:53197:46)
    at DynamicFormService.getValidatorFn (http://localhost:4200/vendor.bundle.js:53211:109)
    at http://localhost:4200/vendor.bundle.js:53227:77
    at Array.map (native)
    at DynamicFormService.getValidators (http://localhost:4200/vendor.bundle.js:53227:33)
    at DynamicFormService.createFormArray (http://localhost:4200/vendor.bundle.js:53239:55)
    at http://localhost:4200/vendor.bundle.js:53248:45
    at Array.forEach (native)_

The code works fine if I set the field invalid if the value is null. Not entirely sure if its an Angular issue or a ng2-dynamic-form issue. Any help or pointers are welcome. Thanks in advance.

**Comment by arjunshankar** [comment]
I am not entirely sure why this was happening. I was able to bypass this condition by giving the element a default value during initialization.

Still would be nice to know the root cause.
