### ISSUE TITLE
AoT build - runtime issue for FormGroup Validator

### ISSUE THREAD

**Issue by arjunshankar** [udos86/ng2-dynamic-forms#420]
Adding a custom validator to a form group. Provided using NG_VALIDATORS as specified in the documentation. Works fine in dev mode. But getting the following error in AoT build. Seems like its failing in "getCustomValidatorFn()" in DynamicFormService.

Stack Trace..
`TypeError: Cannot read property 'hasOwnProperty' of null
    at http://localhost:8088/vendor.f12eff6f2e311f6faf4e.bundle.js:760:98393
    at Array.find (native)
    at t.getCustomValidatorFn (http://localhost:8088/vendor.f12eff6f2e311f6faf4e.bundle.js:760:98337)
    at t.getValidatorFn (http://localhost:8088/vendor.f12eff6f2e311f6faf4e.bundle.js:760:98678)
    at http://localhost:8088/vendor.f12eff6f2e311f6faf4e.bundle.js:760:99181
    at Array.map (native)
    at t.getValidators (http://localhost:8088/vendor.f12eff6f2e311f6faf4e.bundle.js:760:99156)
    at t.createFormArray (http://localhost:8088/vendor.f12eff6f2e311f6faf4e.bundle.js:760:99510)
    at http://localhost:8088/vendor.f12eff6f2e311f6faf4e.bundle.js:760:99746
    at Array.forEach (native)
    at t.createFormGroup (http://localhost:8088/vendor.f12eff6f2e311f6faf4e.bundle.js:760:99691)
    at http://localhost:8088/vendor.f12eff6f2e311f6faf4e.bundle.js:760:99929
    at Array.forEach (native)
    at t.createFormGroup (http://localhost:8088/vendor.f12eff6f2e311f6faf4e.bundle.js:760:99691)`

**Comment by udos86** [comment]
@arjunshankar Coud you please provide the code for your `ValidatorFn`?

**Comment by arjunshankar** [comment]
export function someValidator(fa:FormArray) {
  let totalValue:number = 0;
  if(fa && fa.controls){
    for(var i=0;i<fa.length;i++){
      let fg = fa.controls[i];
      var fc = fg['controls']['someProperty'];
      totalValue += Number(fc.value);
    }
    if(totalValue>=99 && totalValue<=100){
      return null;
    }
    else{
      return {
        someValidator: {
          valid: false
        }
      }
    }
  }
  else{
    return {
      someValidator: {
        valid: false
      }
    };
  }
}


Its basically looping over a bunch of controls in a form array and calculating total of all the fields.

**Comment by udos86** [comment]
@arjunshankar 

Did you exclude your validator function name from mangling as described in chapter on [`Custom Validators`](https://github.com/udos86/ng2-dynamic-forms#custom-validators)?

**Comment by arjunshankar** [comment]
I have not excluded it from mangling since I am using angular cli. I went through the issue list and docs and I understand that mangling was not required anymore. Moreover, other validators on form controls were working perfectly fine.
