### ISSUE TITLE
Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by dt-1980** [udos86/ng2-dynamic-forms#478]
Error: Uncaught (in promise): TypeError: Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at DynamicFormService.webpackJsonp.361.DynamicFormService.createFormGroup (http://localhost:8100/build/0.js:2348:19)
    at new FormsPage (http://localhost:8100/build/0.js:2655:44)
    at createClass (http://localhost:8100/build/vendor.js:11291:26)
    at createDirectiveInstance (http://localhost:8100/build/vendor.js:11109:37)
    at createViewNodes (http://localhost:8100/build/vendor.js:12545:49)
    at createRootView (http://localhost:8100/build/vendor.js:12440:5)
    at callWithDebugContext (http://localhost:8100/build/vendor.js:13823:42)
    at Object.debugCreateRootView [as createRootView] (http://localhost:8100/build/vendor.js:13140:12)
    at ComponentFactory_.create (http://localhost:8100/build/vendor.js:10217:46)
    at ComponentFactoryBoundToModule.create (http://localhost:8100/build/vendor.js:3691:29)
    at c (http://localhost:8100/build/polyfills.js:3:13190)
    at Object.reject (http://localhost:8100/build/polyfills.js:3:12546)
    at NavControllerBase._fireError (http://localhost:8100/build/vendor.js:43700:16)
    at NavControllerBase._failed (http://localhost:8100/build/vendor.js:43688:14)
    at http://localhost:8100/build/vendor.js:43743:59
    at t.invoke (http://localhost:8100/build/polyfills.js:3:8971)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:4248:33)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:8911)
    at r.run (http://localhost:8100/build/polyfills.js:3:4140)
    at http://localhost:8100/build/polyfills.js:3:13731

Ionic Framework: 3.3.0
Ionic App Scripts: 2.1.4
Angular Core: 4.3.5
Angular Compiler CLI: 4.3.5
Node: 6.10.3
OS Platform: Windows 7
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

**Comment by udos86** [comment]
@dt-1980 Hi!

Seems like you're calling `createFormGroup()` the wrong way. The first params needs to be of type `Array<DynamicFormControlModel>` and should not be `undefined`.

**Comment by udos86** [comment]
closed due to inactivity
