### ISSUE TITLE
Error with DynamicRadioGroupModel

### ISSUE THREAD

**Issue by atarix83** [udos86/ng2-dynamic-forms#487]
When I use a DynamicRadioGroupModel in the form model I get this error in infinite loop : 
```
ERROR { TypeError: Cannot set property 'active' of null
    at NgbRadio.updateValue (path\dist\server.js:9208:28)
    at path\dist\server.js:9067:62
    at Set.forEach (native)
    at NgbRadioGroup._updateRadiosValue (path\dist\server.js:9067:22)
    at NgbRadioGroup.onRadioValueUpdate (path\dist\server.js:9052:69)
    at NgbRadio.set [as value] (path\dist\server.js:9158:29)
    at updateProp (path\node_modules\@angular\core\bundles\core.umd.js:11132:37)
    at checkAndUpdateDirectiveInline (path\node_modules\@angular\core\bundles\core.umd.js:10824:19)
    at checkAndUpdateNodeInline (path\node_modules\@angular\core\bundles\core.umd.js:12362:17)
    at checkAndUpdateNode (path\node_modules\@angular\core\bundles\core.umd.js:12301:16)
```

This is the model that I use : 
```
export const MY_DYNAMIC_FORM_MODEL2 = [

  new DynamicInputModel({

    id: 'exampleInput',
    label: 'Example Input',
    maxLength: 42,
    placeholder: 'example input'
  }),

  new DynamicRadioGroupModel<string>({

    id: 'exampleRadioGroup',
    label: 'Example Radio Group',
    options: [
      {
        label: 'Option 1',
        value: 'option-1',
      },
      {
        label: 'Option 2',
        value: 'option-2'
      },
      {
        label: 'Option 3',
        value: 'option-3'
      }
    ],
    value: 'option-3'
  }),

  new DynamicCheckboxModel({

    id: 'exampleCheckbox',
    label: 'I do agree'
  })
];
```

When I remove DynamicRadioGroupModel from the model all works properly.

Any ideas what is wrong here?

Thanks

**Comment by udos86** [comment]
@atarix83 Hi!

Did you already update to ng-bootstrap `beta.2`?

**Comment by atarix83** [comment]
Hi @udos86 

I've updated ng-bootstrap to beta.3 and now it works.

Thanks
