### ISSUE TITLE
Build error : problem with rollup

### ISSUE THREAD

**Issue by jovanracic053** [udos86/ng2-dynamic-forms#494]
During the building phase I've got errors:
Error: Unexpected key 'moduleName' found, expected one of: acorn, amd, banner, cache, context, entry, exports, extend, external, file, footer, format, globals, indent, input, interop, intro, legacy, moduleContext, name, noConflict, onwarn, output, outro, paths, plugins, preferConst, pureExternalModules, sourcemap, sourcemapFile, strict, targets, treeshake, watch
    at validateKeys (C:\...\...\node_modules\rollup\dist\rollup.js:171:11)
    at checkInputOptions (C:\ng2-dynamic-forms-09-2107\ng2-dynamic-forms-master\node_modules\rollup\dist\rollup.js:10154:14)
    at Object.rollup (C:\ng2-dynamic-forms-09-2107\ng2-dynamic-forms-master\node_modules\rollup\dist\rollup.js:10225:3)
    at C:\...\...\node_modules\rollup-stream\index.js:65:19
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by udos86** [comment]
@jovanracic053 Yep, thanks for reporting this.

Rollup introduced some breaking property name changes in the latest version. 

I'll deliver a pull request as soon as possible.

**Comment by playground** [comment]
I'm getting the same error.  What is replacing moduleName?

**Comment by playground** [comment]
Found the documentation to fix the errors.

Need to change the following:
input -> entry
moduleName -> name
